In [7]:
import numpy as np

In [9]:
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

In [10]:
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
np.ones((3,4))
np.zeros((2,3,4),dtype=np.int16)
np.random.random((2,2))
np.empty((3,2))
np.full((2,2),7)
np.arange(10,25,5)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
print(my_array.ndim)
print(my_array.size)
print(my_array.flags)
print(my_array.itemsize)
print(my_array.nbytes)

2
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
8
64


In [13]:
print(len(my_array))
my_array.astype(float)

2


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [14]:
x = np.ones((3,4))
print(x.shape)
y = np.random.random((3,4))
print(y.shape)
x + y

(3, 4)
(3, 4)


array([[1.73778887, 1.8649821 , 1.6079626 , 1.75663986],
       [1.03445466, 1.26438917, 1.29439905, 1.98253206],
       [1.61931867, 1.52441822, 1.55228833, 1.76153565]])

In [15]:
x = np.ones((3,4))
y= np.random.random((5,1,4))
x+y

array([[[1.91772576, 1.67879547, 1.62573049, 1.07667318],
        [1.91772576, 1.67879547, 1.62573049, 1.07667318],
        [1.91772576, 1.67879547, 1.62573049, 1.07667318]],

       [[1.11955728, 1.48116562, 1.27251287, 1.90084864],
        [1.11955728, 1.48116562, 1.27251287, 1.90084864],
        [1.11955728, 1.48116562, 1.27251287, 1.90084864]],

       [[1.35302601, 1.70128268, 1.48061815, 1.24551141],
        [1.35302601, 1.70128268, 1.48061815, 1.24551141],
        [1.35302601, 1.70128268, 1.48061815, 1.24551141]],

       [[1.50239861, 1.03407808, 1.88642162, 1.99520711],
        [1.50239861, 1.03407808, 1.88642162, 1.99520711],
        [1.50239861, 1.03407808, 1.88642162, 1.99520711]],

       [[1.0597343 , 1.99575323, 1.40796837, 1.53009246],
        [1.0597343 , 1.99575323, 1.40796837, 1.53009246],
        [1.0597343 , 1.99575323, 1.40796837, 1.53009246]]])

In [16]:
np.add(x,y)

np.subtract(x,y)

np.multiply(x,y)

np.divide(x,y)

np.remainder(x,y)

array([[[0.08227424, 0.32120453, 0.37426951, 0.0032486 ],
        [0.08227424, 0.32120453, 0.37426951, 0.0032486 ],
        [0.08227424, 0.32120453, 0.37426951, 0.0032486 ]],

       [[0.04354179, 0.03766876, 0.18246138, 0.09915136],
        [0.04354179, 0.03766876, 0.18246138, 0.09915136],
        [0.04354179, 0.03766876, 0.18246138, 0.09915136]],

       [[0.29394798, 0.29871732, 0.0387637 , 0.01795437],
        [0.29394798, 0.29871732, 0.0387637 , 0.01795437],
        [0.29394798, 0.29871732, 0.0387637 , 0.01795437]],

       [[0.49760139, 0.01173579, 0.11357838, 0.00479289],
        [0.49760139, 0.01173579, 0.11357838, 0.00479289],
        [0.49760139, 0.01173579, 0.11357838, 0.00479289]],

       [[0.04425118, 0.00424677, 0.18406326, 0.46990754],
        [0.04425118, 0.00424677, 0.18406326, 0.46990754],
        [0.04425118, 0.00424677, 0.18406326, 0.46990754]]])

In [20]:
a = np.ones((3,4))
b= np.random.random((3,4))
np.logical_and(a,b)
np.logical_or(a,b)
np.logical_not(a,b)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
print(my_array[1])
print(my_2d_array[1][2])
print(my_2d_array[1,2])
print(my_3d_array[1,1,2])

[5 6 7 8]


NameError: name 'my_2d_array' is not defined